version: 2
project_name: echosvr

before:
  hooks:
    - go mod tidy

builds:
  - id: echosvr
    main: ./main.go
    binary: echosvr
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

  - id: echosvr-aix
    main: ./main.go
    binary: echosvr
    env:
      - CGO_ENABLED=0
      - GOPPC64=power8
    goos:
      - aix
    goarch:
      - ppc64
    ldflags:
      - -w

archives:
  - format: tar.gz
    # Use standard names
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
